import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [prompt, setprompt] = useState("")
  const [results, setresults] = useState([])

   const onSubmit =async(e:any)=>{
    e.preventDefault();
    try {
      const response= await fetch('/api/openaiAPI',{
        method:"POST",
        headers:{
          "Content-Type":"application/json"
        },
        body:JSON.stringify({prompt})
      })
      const data =await response.json();
      if(response.status !== 200){
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }
      setresults(data.result)
    } catch (error:any) {
      console.error(error);
      alert(error.message);
    }

   }

  return (
    <>
      <Head>
        <title>OPEN AI AND PINECONE TEXT EMBEDDING</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className={styles.main}>
        <h3>TEXT EMBEDDING AND VECTOR SEARCH <br/> THROUGH OPEN AI AND PINECONE</h3>
        <form onSubmit={onSubmit}>
          <input
            type="text"
            name="prompt"
            placeholder="Enter prompt message"
            value={prompt}
            onChange={(e) => setprompt(e.target.value)}
          />
          <input type="submit" value="Generate Vector" />
        </form>
        <div className={styles.result}>{JSON.stringify(results)}</div>
      </main>
    </>
  )
}
